#!/bin/bash

echo "=============================================="
echo "  LiteRead - Android Document Reader"
echo "=============================================="
echo ""
echo "This is an Android application project."
echo "Android apps produce APK files for mobile devices"
echo "and cannot run directly in a web browser."
echo ""
echo "Project Structure:"
echo "-----------------"
echo "- app/src/main/java/  - Kotlin source code"
echo "- app/src/main/res/   - Android resources"
echo "- app/build.gradle.kts - App dependencies"
echo ""
echo "To build this project, you need:"
echo "1. Android Studio (recommended)"
echo "2. Or command line with Android SDK:"
echo "   - Install Android SDK"
echo "   - Run: ./gradlew assembleDebug"
echo "   - APK will be at: app/build/outputs/apk/debug/"
echo ""
echo "Features:"
echo "- PDF, EPUB, TXT, MOBI document reading"
echo "- 4 beautiful themes (Light, Dark, Sepia, AMOLED)"
echo "- Bookmarks and reading history"
echo "- Ultra-lightweight (~10MB APK)"
echo ""
echo "For more info, see README.md"
echo "=============================================="

while true; do
    sleep 60
done
